export const SET_PHONE_DOCUMENTS = 'SET_PHONE_DOCUMENTs';
export const SET_ACCESSORIES_DOCUMENTS = 'SET_ACCESSORIES_DOCUMENTS';

export const SET_PRODUCT_DETAILS = 'SET_PRODUCT_DETAILS';

export const SET_BIGPICTURE_UPLOAD = 'SET_BIGPICTURE_UPLOAD';
export const SET_BIGPICTURE_VIEW = 'SET_BIGPICTURE_VIEW';