export const SET_VISIBLE_DOCUMENTS = 'SET_VISIBLE_DOCUMENTS';
export const SET_TOTAL_ACCESSORIES_DOCUMENTS = 'SET_TOTAL_ACCESSORIES_DOCUMENTS';

export const SET_VISIBLE_PHONE_DOCUMENTS = 'SET_VISIBLE_PHONE_DOCUMENTS';
export const SET_VISIBLE_ACCESSORIES_DOCUMENTS = 'SET_VISIBLE_ACCESSORIES_DOCUMENTS';

export const SET_PRODUCT_DETAILS = 'SET_PRODUCT_DETAILS';

export const SET_BIGPICTURE_UPLOAD = 'SET_BIGPICTURE_UPLOAD';
export const SET_BIGPICTURE_VIEW = 'SET_BIGPICTURE_VIEW';

export const SET_USER = 'SET_USER';
export const CLEAN_USER = 'CLEAN_USER';
export const SET_USER_ERROR = 'SET_USER_ERROR';

export const SEARCH_PHONE = 'SEARCH_PHONE';